var config = {}

config.scraper = {
    interval : 86400000
}

config.countries = [
    { code : 'ABW', names : ['Aruba'] },
    { code : 'AFG', names : ['Afghanistan'] },
    { code : 'AGO', names : ['Angola'] },
    { code : 'AIA', names : ['Anguilla'] },
    { code : 'ALA', names : ['Åland Islands'] },
    { code : 'ALB', names : ['Albania'] },
    { code : 'AND', names : ['Andorra'] },
    { code : 'ARE', names : ['United Arab Emirates', 'UAE'] },
    { code : 'ARG', names : ['Argentina'] },
    { code : 'ARM', names : ['Armenia'] },
    { code : 'ASM', names : ['American Samoa'] },
    { code : 'ATA', names : ['Antarctica'] },
    { code : 'ATF', names : ['French Southern Territories'] },
    { code : 'ATG', names : ['Antigua and Barbuda'] },
    { code : 'AUS', names : ['Australia'] },
    { code : 'AUT', names : ['Austria'] },
    { code : 'AZE', names : ['Azerbaijan'] },
    { code : 'BDI', names : ['Burundi'] },
    { code : 'BEL', names : ['Belgium'] },
    { code : 'BEN', names : ['Benin'] },
    { code : 'BES', names : ['Bonaire, Sint Eustatius and Saba'] },
    { code : 'BFA', names : ['Burkina Faso'] },
    { code : 'BGD', names : ['Bangladesh'] },
    { code : 'BGR', names : ['Bulgaria'] },
    { code : 'BHR', names : ['Bahrain'] },
    { code : 'BHS', names : ['Bahamas'] },
    { code : 'BIH', names : ['Bosnia and Herzegovina'] },
    { code : 'BLM', names : ['Saint Barthélemy'] },
    { code : 'BLR', names : ['Belarus'] },
    { code : 'BLZ', names : ['Belize'] },
    { code : 'BMU', names : ['Bermuda'] },
    { code : 'BOL', names : ['Bolivia, Plurinational State of'] },
    { code : 'BRA', names : ['Brazil'] },
    { code : 'BRB', names : ['Barbados'] },
    { code : 'BRN', names : ['Brunei Darussalam'] },
    { code : 'BTN', names : ['Bhutan'] },
    { code : 'BVT', names : ['Bouvet Island'] },
    { code : 'BWA', names : ['Botswana'] },
    { code : 'CAF', names : ['Central African Republic'] },
    { code : 'CAN', names : ['Canada'] },
    { code : 'CCK', names : ['Cocos (Keeling) Islands'] },
    { code : 'CHE', names : ['Switzerland'] },
    { code : 'CHL', names : ['Chile'] },
    { code : 'CHN', names : ['China'] },
    { code : 'CIV', names : ['Côte d\'Ivoire', 'Ivory Coast'] },
    { code : 'CMR', names : ['Cameroon'] },
    { code : 'COD', names : ['Congo, the Democratic Republic of the'] },
    { code : 'COG', names : ['Congo'] },
    { code : 'COK', names : ['Cook Islands'] },
    { code : 'COL', names : ['Colombia'] },
    { code : 'COM', names : ['Comoros'] },
    { code : 'CPV', names : ['Cabo Verde'] },
    { code : 'CRI', names : ['Costa Rica'] },
    { code : 'CUB', names : ['Cuba'] },
    { code : 'CUW', names : ['Curaçao'] },
    { code : 'CXR', names : ['Christmas Island'] },
    { code : 'CYM', names : ['Cayman Islands'] },
    { code : 'CYP', names : ['Cyprus'] },
    { code : 'CZE', names : ['Czech Republic'] },
    { code : 'DEU', names : ['Germany'] },
    { code : 'DJI', names : ['Djibouti'] },
    { code : 'DMA', names : ['Dominica'] },
    { code : 'DNK', names : ['Denmark'] },
    { code : 'DOM', names : ['Dominican Republic'] },
    { code : 'DZA', names : ['Algeria'] },
    { code : 'ECU', names : ['Ecuador'] },
    { code : 'EGY', names : ['Egypt'] },
    { code : 'ERI', names : ['Eritrea'] },
    { code : 'ESH', names : ['Western Sahara'] },
    { code : 'ESP', names : ['Spain'] },
    { code : 'EST', names : ['Estonia'] },
    { code : 'ETH', names : ['Ethiopia'] },
    { code : 'FIN', names : ['Finland'] },
    { code : 'FJI', names : ['Fiji'] },
    { code : 'FLK', names : ['Falkland Islands', 'Malvinas'] },
    { code : 'FRA', names : ['France'] },
    { code : 'FRO', names : ['Faroe Islands'] },
    { code : 'FSM', names : ['Micronesia, Federated States of'] },
    { code : 'GAB', names : ['Gabon'] },
    { code : 'GBR', names : ['United Kingdom', 'UK', 'Great Britain', 'England', 'Scotland'] },
    { code : 'GEO', names : ['Georgia'] },
    { code : 'GGY', names : ['Guernsey'] },
    { code : 'GHA', names : ['Ghana'] },
    { code : 'GIB', names : ['Gibraltar'] },
    { code : 'GIN', names : ['Guinea'] },
    { code : 'GLP', names : ['Guadeloupe'] },
    { code : 'GMB', names : ['Gambia'] },
    { code : 'GNB', names : ['Guinea-Bissau'] },
    { code : 'GNQ', names : ['Equatorial Guinea'] },
    { code : 'GRC', names : ['Greece'] },
    { code : 'GRD', names : ['Grenada'] },
    { code : 'GRL', names : ['Greenland'] },
    { code : 'GTM', names : ['Guatemala'] },
    { code : 'GUF', names : ['French Guiana'] },
    { code : 'GUM', names : ['Guam'] },
    { code : 'GUY', names : ['Guyana'] },
    { code : 'HKG', names : ['Hong Kong'] },
    { code : 'HMD', names : ['Heard Island and McDonald Islands'] },
    { code : 'HND', names : ['Honduras'] },
    { code : 'HRV', names : ['Croatia'] },
    { code : 'HTI', names : ['Haiti'] },
    { code : 'HUN', names : ['Hungary'] },
    { code : 'IDN', names : ['Indonesia'] },
    { code : 'IMN', names : ['Isle of Man'] },
    { code : 'IND', names : ['India'] },
    { code : 'IOT', names : ['British Indian Ocean Territory'] },
    { code : 'IRL', names : ['Ireland'] },
    { code : 'IRN', names : ['Iran, Islamic Republic of', 'Iran'] },
    { code : 'IRQ', names : ['Iraq'] },
    { code : 'ISL', names : ['Iceland'] },
    { code : 'ISR', names : ['Israel'] },
    { code : 'ITA', names : ['Italy'] },
    { code : 'JAM', names : ['Jamaica'] },
    { code : 'JEY', names : ['Jersey'] },
    { code : 'JOR', names : ['Jordan'] },
    { code : 'JPN', names : ['Japan'] },
    { code : 'KAZ', names : ['Kazakhstan'] },
    { code : 'KEN', names : ['Kenya'] },
    { code : 'KGZ', names : ['Kyrgyzstan'] },
    { code : 'KHM', names : ['Cambodia'] },
    { code : 'KIR', names : ['Kiribati'] },
    { code : 'KNA', names : ['Saint Kitts and Nevis'] },
    { code : 'KOR', names : ['Korea, Republic of', 'South Korea'] },
    { code : 'KWT', names : ['Kuwait'] },
    { code : 'LAO', names : ['Lao People\'s Democratic Republic', 'Lao'] },
    { code : 'LBN', names : ['Lebanon'] },
    { code : 'LBR', names : ['Liberia'] },
    { code : 'LBY', names : ['Libya'] },
    { code : 'LCA', names : ['Saint Lucia'] },
    { code : 'LIE', names : ['Liechtenstein'] },
    { code : 'LKA', names : ['Sri Lanka'] },
    { code : 'LSO', names : ['Lesotho'] },
    { code : 'LTU', names : ['Lithuania'] },
    { code : 'LUX', names : ['Luxembourg'] },
    { code : 'LVA', names : ['Latvia'] },
    { code : 'MAC', names : ['Macao'] },
    { code : 'MAF', names : ['Saint Martin'] },
    { code : 'MAR', names : ['Morocco'] },
    { code : 'MCO', names : ['Monaco'] },
    { code : 'MDA', names : ['Moldova, Republic of', 'Moldova'] },
    { code : 'MDG', names : ['Madagascar'] },
    { code : 'MDV', names : ['Maldives'] },
    { code : 'MEX', names : ['Mexico'] },
    { code : 'MHL', names : ['Marshall Islands'] },
    { code : 'MKD', names : ['Macedonia, the former Yugoslav Republic of', 'Macedonia'] },
    { code : 'MLI', names : ['Mali'] },
    { code : 'MLT', names : ['Malta'] },
    { code : 'MMR', names : ['Myanmar'] },
    { code : 'MNE', names : ['Montenegro'] },
    { code : 'MNG', names : ['Mongolia'] },
    { code : 'MNP', names : ['Northern Mariana Islands'] },
    { code : 'MOZ', names : ['Mozambique'] },
    { code : 'MRT', names : ['Mauritania'] },
    { code : 'MSR', names : ['Montserrat'] },
    { code : 'MTQ', names : ['Martinique'] },
    { code : 'MUS', names : ['Mauritius'] },
    { code : 'MWI', names : ['Malawi'] },
    { code : 'MYS', names : ['Malaysia'] },
    { code : 'MYT', names : ['Mayotte'] },
    { code : 'NAM', names : ['Namibia'] },
    { code : 'NCL', names : ['New Caledonia'] },
    { code : 'NER', names : ['Niger'] },
    { code : 'NFK', names : ['Norfolk Island'] },
    { code : 'NGA', names : ['Nigeria'] },
    { code : 'NIC', names : ['Nicaragua'] },
    { code : 'NIU', names : ['Niue'] },
    { code : 'NLD', names : ['Netherlands'] },
    { code : 'NOR', names : ['Norway'] },
    { code : 'NPL', names : ['Nepal'] },
    { code : 'NRU', names : ['Nauru'] },
    { code : 'NZL', names : ['New Zealand'] },
    { code : 'OMN', names : ['Oman'] },
    { code : 'PAK', names : ['Pakistan'] },
    { code : 'PAN', names : ['Panama'] },
    { code : 'PCN', names : ['Pitcairn'] },
    { code : 'PER', names : ['Peru'] },
    { code : 'PHL', names : ['Philippines'] },
    { code : 'PLW', names : ['Palau'] },
    { code : 'PNG', names : ['Papua New Guinea'] },
    { code : 'POL', names : ['Poland'] },
    { code : 'PRI', names : ['Puerto Rico'] },
    { code : 'PRK', names : ['Korea, Democratic People\'s Republic of', 'North Korea', 'PRK'] },
    { code : 'PRT', names : ['Portugal'] },
    { code : 'PRY', names : ['Paraguay'] },
    { code : 'PSE', names : ['Palestine, State of', 'Palestine'] },
    { code : 'PYF', names : ['French Polynesia'] },
    { code : 'QAT', names : ['Qatar'] },
    { code : 'REU', names : ['Réunion'] },
    { code : 'ROU', names : ['Romania'] },
    { code : 'RUS', names : ['Russian Federation'] },
    { code : 'RWA', names : ['Rwanda'] },
    { code : 'SAU', names : ['Saudi Arabia'] },
    { code : 'SDN', names : ['Sudan'] },
    { code : 'SEN', names : ['Senegal'] },
    { code : 'SGP', names : ['Singapore'] },
    { code : 'SGS', names : ['South Georgia and the South Sandwich Islands'] },
    { code : 'SHN', names : ['Saint Helena, Ascension and Tristan da Cunha'] },
    { code : 'SJM', names : ['Svalbard and Jan Mayen'] },
    { code : 'SLB', names : ['Solomon Islands'] },
    { code : 'SLE', names : ['Sierra Leone'] },
    { code : 'SLV', names : ['El Salvador'] },
    { code : 'SMR', names : ['San Marino'] },
    { code : 'SOM', names : ['Somalia'] },
    { code : 'SPM', names : ['Saint Pierre and Miquelon'] },
    { code : 'SRB', names : ['Serbia'] },
    { code : 'SSD', names : ['South Sudan'] },
    { code : 'STP', names : ['Sao Tome and Principe'] },
    { code : 'SUR', names : ['Suriname'] },
    { code : 'SVK', names : ['Slovakia'] },
    { code : 'SVN', names : ['Slovenia'] },
    { code : 'SWE', names : ['Sweden'] },
    { code : 'SWZ', names : ['Swaziland'] },
    { code : 'SXM', names : ['Sint Maarten (Dutch part)'] },
    { code : 'SYC', names : ['Seychelles'] },
    { code : 'SYR', names : ['Syrian Arab Republic'] },
    { code : 'TCA', names : ['Turks and Caicos Islands'] },
    { code : 'TCD', names : ['Chad'] },
    { code : 'TGO', names : ['Togo'] },
    { code : 'THA', names : ['Thailand'] },
    { code : 'TJK', names : ['Tajikistan'] },
    { code : 'TKL', names : ['Tokelau'] },
    { code : 'TKM', names : ['Turkmenistan'] },
    { code : 'TLS', names : ['Timor-Leste'] },
    { code : 'TON', names : ['Tonga'] },
    { code : 'TTO', names : ['Trinidad and Tobago', 'Trinidad'] },
    { code : 'TUN', names : ['Tunisia'] },
    { code : 'TUR', names : ['Turkey'] },
    { code : 'TUV', names : ['Tuvalu'] },
    { code : 'TWN', names : ['Taiwan, Province of China', 'Taiwan'] },
    { code : 'TZA', names : ['Tanzania, United Republic of', 'Tanzania'] },
    { code : 'UGA', names : ['Uganda'] },
    { code : 'UKR', names : ['Ukraine'] },
    { code : 'UMI', names : ['United States Minor Outlying Islands'] },
    { code : 'URY', names : ['Uruguay'] },
    { code : 'USA', names : ['United States', 'United States of America', 'America', 'US'] },
    { code : 'UZB', names : ['Uzbekistan'] },
    { code : 'VAT', names : ['Holy See (Vatican City State)'] },
    { code : 'VCT', names : ['Saint Vincent and the Grenadines'] },
    { code : 'VEN', names : ['Venezuela, Bolivarian Republic of', 'Venezuela'] },
    { code : 'VGB', names : ['Virgin Islands, British'] },
    { code : 'VIR', names : ['Virgin Islands, U.S.', 'Virgin Islands'] },
    { code : 'VNM', names : ['Viet Nam', 'Vietnam'] },
    { code : 'VUT', names : ['Vanuatu'] },
    { code : 'WLF', names : ['Wallis and Futuna'] },
    { code : 'WSM', names : ['Samoa'] },
    { code : 'YEM', names : ['Yemen'] },
    { code : 'ZAF', names : ['South Africa'] },
    { code : 'ZMB', names : ['Zambia'] },
    { code : 'ZWE', names : ['Zimbabwe'] }
];

config.keywords = [
    { relevance : 2, term : 'conflict' },
    { relevance : 5, term : 'war' },
    { relevance : 1, term : 'battle' },
    { relevance : 5, term : 'casualties' },
    { relevance : 2, term : 'casualty' },
    { relevance : 1, term : 'dead' },
    { relevance : 1, term : 'violence' },
    { relevance : 1, term : 'evacuation' },
    { relevance : 1, term : 'evacuate' },
    { relevance : 5, term : 'wounded' },
    { relevance : 2, term : 'killed' },
    { relevance : 8, term : 'soliders' },
    { relevance : 8, term : 'solider' },
    { relevance : 1, term : 'attack' },
    { relevance : 1, term : 'shot' },
    { relevance : 1, term : 'shots' },
    { relevance : 1, term : 'shootings' },
    { relevance : 1, term : 'shooting' },
    { relevance : 8, term : 'rocket' },
    { relevance : 8, term : 'rockets' },
    { relevance : 8, term : 'grenades' },
    { relevance : 5, term : 'captured' },
    { relevance : 8, term : 'bombing' },
    { relevance : 8, term : 'bombs' },
    { relevance : 5, term : 'bombers' },
    { relevance : 8, term : 'missile' },
    { relevance : 8, term : 'missiles' },
    { relevance : 9, term : 'militia' },
    { relevance : 4, term : 'fighters' },
    { relevance : 3, term : 'hostage' },
    { relevance : 3, term : 'hostages' },
    { relevance : 5, term : 'military' }
];

config.conflictThreshold =  0.05;

config.conflictKeywordRepetitionThreshold =  3;

config.channels = [{
    name : 'BBC',
    id : 'SourceBbc',
    enabled : true,
    domain : 'http://www.bbc.co.uk/',
    url : 'http://feeds.bbci.co.uk/news/world/rss.xml',
    articleUrl : 'channel > item > link',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : '.story-header, .story-body__h1, .article p.introduction, .unit__title',
        story : '.story-body p'
    }
}, {
    name : 'Al Jazeera',
    id : 'SourceAlJazeera',
    enabled : true,
    domain : 'http://www.aljazeera.com/',
    url : 'http://www.aljazeera.com/xml/rss/all.xml',
    articleUrl : 'channel > item > link',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : 'h1.heading-story',
        story : '#article-topics a, #article-body p'
    }
}, {
    name : 'Reuters',
    id : 'SourceReuters',
    enabled : true,
    domain : 'http://uk.reuters.com/',
    url : 'http://mf.feeds.reuters.com/reuters/UKWorldNews',
    articleUrl : 'channel > item > link',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : 'h1.article-headline',
        story : '#articleText p'
    }
}, {
    name : 'Wikinews',
    id : 'SourceWikinews',
    enabled : true,
    domain : 'https://en.wikinews.org/',
    url : 'https://en.wikinews.org/w/index.php?title=Special:NewsFeed&feed=atom&categories=Published%7CPolitics_and_conflicts&notcategories=No%20publish%7Cdisputed&namespace=0&ordermethod=categoryadd&stablepages=only',
    articleUrl : 'feed > entry > id',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : 'h1.firstHeading',
        story : '#bodyContent p'
    }
}, {
    name : 'Independant',
    id : 'SourceIndependant',
    enabled : true,
    domain : 'http://www.independent.co.uk/',
    url : 'http://rss.feedsportal.com/c/266/f/3503/index.rss',
    articleUrl : 'channel > item > guid',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : 'h1.title',
        story : '#main p'
    }
}, {
    name : 'CNN',
    id : 'SourceCNN',
    enabled : true,
    domain : 'http://edition.cnn.com/',
    url : 'http://rss.cnn.com/rss/edition_world.rss',
    articleUrl : 'channel > item > guid',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : 'h1.pg-headline',
        story : '#body-text p'
    }
}, {
    name : 'Washington Post',
    id : 'SourceWashingtonPost',
    enabled : true,
    domain : 'http://washingtonpost.com',
    url : 'http://feeds.washingtonpost.com/rss/world',
    articleUrl : 'channel > item > link',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : '#article-topper h1',
        story : '#article-body p'
    }
}, {
    name : 'Guardian',
    id : 'SourceGuardian',
    enabled : true,
    domain : 'http://www.theguardian.com',
    url : 'http://www.theguardian.com/world/rss',
    articleUrl : 'channel > item > guid',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : 'h1.content__headline',
        story : '.content__article-body p'
    }
}, {
    name : 'Xinhua',
    id : 'SourceXinhua',
    enabled : true,
    domain : 'http://www.xinhuanet.com',
    url : 'http://www.xinhuanet.com/english/rss/worldrss.xml',
    articleUrl : 'channel > item > link',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : '#Title',
        story : '#Content p'
    }
}, {
    name : 'Telegraph',
    id : 'SourceTelegraph',
    enabled : true,
    domain : 'http://www.telegraph.co.uk',
    url : 'http://www.telegraph.co.uk/news/worldnews/rss',
    articleUrl : 'channel > item > guid',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : '.storyHead h1',
        story : '#mainBodyArea p'
    }
}, {
    name : 'Pravdu',
    id : 'SourcePravdu',
    enabled : true,
    domain : 'http://english.pravda.ru/',
    url : 'http://english.pravda.ru/world/export-articles.xml',
    articleUrl : 'channel > item > link',
    isUrlAttribute : false,
    isXml : true,
    isConflict : false,
    article : {
        headline : '#article h1',
        story : '#article p'
    }
}];



module.exports = config;